In [1]:
from master_dac.rld import stk

In [2]:
from stable_baselines3 import PPO, A2C
from stable_baselines3.common.env_util import make_vec_env
from stk_actor.agent import UnifiedSACPolicy
from stk_actor.wrappers import PreprocessObservationWrapper
import torch

from pystk2_gymnasium import AgentSpec

vec_env = make_vec_env("supertuxkart/flattened_multidiscrete-v0", seed=0,
                        # wrapper_class=lambda x : ObsTimeExtensionWrapper(PreprocessObservationWrapper(x)), 
                        wrapper_class=lambda x : (PreprocessObservationWrapper(x)), 
                       n_envs=1, env_kwargs={
    'render_mode':None, 'agent':AgentSpec(use_ai=False, name="walid"),  #'track':'abyss', #'num_kart':2, 'difficulty':0
})

# net_arch=[512,512,512]
# activation_fn=torch.nn.SiLU
# filename = 'policy_512_512_512_SiLU_2_statedict'

# net_arch=[512,512,512,512,512]
net_arch=[1024,1024,1024]
activation_fn=torch.nn.Tanh
# filename = 'policy_512_512_512_512_SiLU_3_statedict'
# filename = 'airl_policy_512_512_512_512_SiLU_statedict'
# filename = 'policy_normed_512_512_512_512_SiLU_statedict'
# filename = 'policy_normed_128_128_SiLU_statedict'
filename = 'policy_normed_1024_1024_1024_Tanh_statedict'

model = PPO(
        "MlpPolicy", 
        vec_env, 
        verbose=1, 
        policy_kwargs = dict(net_arch=net_arch, activation_fn=activation_fn,), 
        device='cpu',
        n_steps=5,
        tensorboard_log="./outputs/"
)
action_dims = [space.n for space in vec_env.action_space]
unified_policy = UnifiedSACPolicy(
    vec_env.observation_space, 
    action_dims, 
    net_arch=net_arch, 
    activation_fn=activation_fn
)
unified_policy.load_state_dict(torch.load(filename))
model.policy.load_state_dict(unified_policy.shared.state_dict())
# model.policy.load_state_dict(torch.load(filename))
vec_env.close()
# model = PPO.load("ppti_ppo_1500", custom_objects={'policy_kwargs' :  dict(net_arch=net_arch, activation_fn=activation_fn), })
model = PPO.load("ppti_ppo2_1024_batch128_clip01_ent0001", custom_objects={'policy_kwargs' :  dict(net_arch=net_arch, activation_fn=activation_fn), })
mean = torch.load('buffer_mean', map_location='cpu')
std = torch.load('buffer_std', map_location='cpu')

..:: Antarctica Rendering Engine 2.0 ::..


/Users/walidthekraken/VISA FRANCE/M2/RLD/stk_project/stk_actor/wrappers.py:119: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.mean = torch.load(mod_path/'buffer_mean', 

Using cpu device


/var/folders/5b/wsyz4crx22bg_7tpsgbw3tzw0000gn/T/ipykernel_8303/1675744499.py:45: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  unified_policy.load_state_dict(torch.load(fil

In [3]:
torch.save(PPO.load("ppti_ppo2_1024_batch128_clip01_ent0001", custom_objects={'policy_kwargs' :  dict(net_arch=net_arch, activation_fn=activation_fn), }).policy.state_dict(), 'ppo_policy_normed_1024_1024_1024_Tanh_statedict')

OrderedDict([('mlp_extractor.policy_net.0.weight',
              tensor([[-0.0517,  0.1053, -0.1528,  ...,  0.0874, -0.0312,  0.2022],
                      [ 0.0108, -0.0161,  0.0005,  ...,  0.0709, -0.0334, -0.0778],
                      [-0.0469,  0.1427,  0.0866,  ..., -0.0344,  0.1868,  0.1551],
                      ...,
                      [-0.1735,  0.0295, -0.0134,  ..., -0.1557, -0.1369, -0.0865],
                      [ 0.1398,  0.1431, -0.2140,  ...,  0.0770, -0.0463, -0.1501],
                      [-0.0193, -0.0695, -0.3339,  ...,  0.1387, -0.1212,  0.0193]])),
             ('mlp_extractor.policy_net.0.bias',
              tensor([ 0.1191,  0.3512, -0.5008,  ...,  0.4422, -0.4249, -0.4465])),
             ('mlp_extractor.policy_net.2.weight',
              tensor([[ 0.2439, -0.0286, -0.0594,  ...,  0.1734,  0.1249, -0.0187],
                      [-0.2689,  0.2392,  0.4162,  ...,  0.0909, -0.2094, -0.0843],
                      [ 0.2172, -0.1364, -0.0695,  ...,  0.283

In [3]:
# mean.tolist()

In [4]:
# std.tolist()

In [ ]:
# 'fortmagma',
# 'ravenbridge_mansion',
# 'snowmountain',
# 'cocoa_temple',
# 'sandtrack',    
# 'scotland', 
# 'stk_enterprise',
# 'volcano_island', # 1104
# 'xr591', # 864
from stk_actor.wrappers import StuckStopWrapper


tracks = [
    # 'black_forest',
    # 'olivermath', # 244
    # 'minigolf', # 434
    # 'gran_paradiso_island', # 683
    # 'candela_city', # 521
    # 'mines', # 639
    # 'snowmountain', # 589
    # 'abyss', # 612
    # 'cornfield_crossing', # 638
    # 'hacienda', # 581
    # 'lighthouse', # 452
    # 'snowtuxpeak', # 482
    # 'zengarden', # 356
# 
# 
    # 'fortmagma',
    # 'ravenbridge_mansion',
    # 'snowmountain',
    # 'cocoa_temple',
    # 'sandtrack',    
    #'scotland', 
    # 'stk_enterprise',
    # 'volcano_island', # 1104
    'xr591', # 864        

]
for track in tracks:
    while True:
        vec_env = make_vec_env("supertuxkart/flattened_multidiscrete-v0", #seed=0,
                            # wrapper_class=lambda x : ObsTimeExtensionWrapper(PreprocessObservationWrapper(x)), 
                            wrapper_class=lambda x : (
                                StuckStopWrapper(
                                    PreprocessObservationWrapper(x, ret_dict=False, norm=False),
                                    n=48,
                                )
                            ), 
                        n_envs=1, env_kwargs={
        'render_mode':"human", 'agent':AgentSpec(use_ai=False, name="walid"), 'laps':1, 
        'track':track,
        'num_kart':12, 'difficulty':2
        })
        obs = vec_env.reset()
        dones = [False]
        ix = 0
        while (True and not any(dones)):
            
            obs = torch.tensor(obs)
            
            obs = (obs - mean) / (std + 1e-8)
            action, _states = model.predict(obs, deterministic=False)
            obs, rewards, dones, info = vec_env.step(action)
            vec_env.render("human")
            # print(dones)
            ix += 1
            if ix == 1500:
                break
        print(track, ix)
        vec_env.close()



            




/Users/walidthekraken/VISA FRANCE/M2/RLD/stk_project/stk_actor/wrappers.py:119: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.mean = torch.load(mod_path/'buffer_mean', 

..:: Antarctica Rendering Engine 2.0 ::..


2025-01-23 15:50:32.615 python[8253:308048] +[IMKClient subclass]: chose IMKClient_Modern
2025-01-23 15:50:32.615 python[8253:308048] +[IMKInputSession subclass]: chose IMKInputSession_Modern
/opt/homebrew/Caskroom/miniforge/base/envs/bbrl/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:335: UserWarning: WARN: No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps.
  logger.warn(


xr591 692
..:: Antarctica Rendering Engine 2.0 ::..


2025-01-23 15:50:52.077 python[8255:308268] +[IMKClient subclass]: chose IMKClient_Modern
2025-01-23 15:50:52.077 python[8255:308268] +[IMKInputSession subclass]: chose IMKInputSession_Modern


xr591 649
..:: Antarctica Rendering Engine 2.0 ::..


2025-01-23 15:51:11.050 python[8257:308562] +[IMKClient subclass]: chose IMKClient_Modern
2025-01-23 15:51:11.050 python[8257:308562] +[IMKInputSession subclass]: chose IMKInputSession_Modern


xr591 733
..:: Antarctica Rendering Engine 2.0 ::..


In [6]:
# import torch
# torch.save( model.policy.state_dict(), 'ppo_policy_512_512_512_512_SiLU_4_statedict')

In [7]:
vec_env.envs[0]

<StuckStopWrapper<PreprocessObservationWrapper<Monitor<FlattenerWrapper<DiscreteActionsWrapper<PolarObservations<ConstantSizedObservations<TimeLimit<OrderEnforcing<PassiveEnvChecker<STKRaceEnv<supertuxkart/flattened_multidiscrete-v0>>>>>>>>>>>>